language: go

go:
  - 1.9

before_install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/alecthomas/gometalinter
  - go get github.com/mattn/goveralls

install:
  - gometalinter -i --vendored-linters
  - dep ensure

script:
  - gofmt -l *.go
  - goimports -l *.go
  - test "$(gofmt -l *.go | wc -l)" -eq "0"
  - test "$(goimports -l *.go | wc -l)" -eq "0"
  - gometalinter --vendor ./...
  - go test -race -covermode=atomic -coverprofile=coverage.txt
  - goveralls -covermode=atomic -coverprofile=coverage.txt -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
