language: go

go:
  - 1.9

before_install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/alecthomas/gometalinter
  - gometalinter -i --vendored-linters

install:
  - dep ensure

script:
  - gometalinter --vendor ./...
  - go test --cover ./...
