language: go

go:
  - 1.9

before_install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/alecthomas/gometalinter
  - go get github.com/mattn/goveralls

install:
  - gometalinter -i --vendored-linters
  - dep ensure

script:
  - gometalinter --vendor ./...
  - go test -race -covermode=atomic -coverprofile=profile.cov
  - goveralls -covermode=atomic -coverprofile=profile.cov -service=travis-ci
